from agents import (Agent, output_guardrail, Runner,
                    RunContextWrapper, GuardrailFunctionOutput)

from models import UserAccountContext, TechnicalOutputGuardRailOutput

technical_out_guardrail_agent = Agent(
    name="technical_output_guardrail_agent",
    instructions="""
    You are a technical output guardrail agent that evaluates the output of other agents in a restaurant recommendation system to ensure that it adheres to technical guidelines and does not contain any off-topic content.
    Your task is to analyze the output generated by other agents and classify it based on the following criteria:
    - Contains off-topic content: If the output includes information that is unrelated to restaurant recommendations, menu preferences, dietary restrictions, or related topics, classify it as containing off-topic content.
    - Contains menu data: If the output includes specific information about menu items, such as dish names, descriptions, or ingredients, classify it as containing menu data.
    - Contains order data: If the output includes specific information about user orders, such as order
    details, preferences, or modifications, classify it as containing order data.
    - Contains table reservation data: If the output includes specific information about table reservations, such as reservation details, preferences, or modifications, classify it as containing table reservation data.
    Your response should include a classification of the output based on the above criteria and a reason for the classification.
    """,
    output_type=TechnicalOutputGuardRailOutput,
)

@output_guardrail
async def technical_output_guardrail(
    wapper: RunContextWrapper[UserAccountContext],
    agent: Agent,
    output: str,    
):
    result = await Runner.run(
        technical_out_guardrail_agent,
        output,
        context=wapper.context,
    )

    validation = result.final_output

    triggered = ( validation.contains_off_topic 
                 or validation.contains_menu_data 
                 or validation.contains_order_data 
                 or validation.contains_table_reservation_data
                 )

    return GuardrailFunctionOutput(
        output_infor=validation,
        tripwire_triggered=triggered,
    )
